- name: "[Arch] Install i3"
  community.general.pacman:
    name: i3-gaps
    state: present
  when: ansible_distribution == 'Archlinux'
  become: true
- name: "[Arch] Install feh" 
  community.general.pacman:
    name: feh
    state: present
  when: ansible_distribution == 'Archlinux'
  become: true
- name: "[Arch] Install picom" 
  community.general.pacman:
    name: picom
    state: present
  when: ansible_distribution == 'Archlinux'
  become: true
