---
- name: "[MacOS] Check if Homebrew is already installed"
  stat:
    path: /usr/local/bin/brew
  register: b
  when: ansible_distribution == 'MacOSX'
- name: "[MacOS] Install Homebrew"
  shell: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  when: ansible_distribution == 'MacOSX' and not b.stat.exists

