- name: "[MacOS] Install Neovim"
  community.general.homebrew:
    name: nvim
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install Neovim"
  become: true
  community.general.pacman:
    name: neovim
    state: present
  when: ansible_distribution == 'Archlinux'
- name: "Setup Neovim"
  shell: stow nvim
  args:
    chdir: ~/dotfiles
- name: "[MacOS] Install Rg"
  community.general.homebrew:
    name: ripgrep
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install Rg"
  become: true
  community.general.pacman:
    name: ripgrep
    state: present
  when: ansible_distribution == 'Archlinux'
