- name: "[MacOS] Install Stow"
  community.general.homebrew:
    name: stow
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install Stow"
  become: true
  community.general.pacman:
    name: stow
    state: present
  when: ansible_distribution == 'Archlinux'
