- name: "[MacOS] Install Alacritty"
  community.general.homebrew:
    name: alacritty
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install Alacritty"
  become: true
  community.general.pacman:
    name: alacritty
    state: present
  when: ansible_distribution == 'Archlinux'
- name: "Setup Alacritty"
  shell: stow alacritty
  args:
    chdir: ~/dotfiles

- name: "[MacOS] Install Starship"
  community.general.homebrew:
    name: starship
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install Starship"
  become: true
  community.general.pacman:
    name: starship
    state: present
  when: ansible_distribution == 'Archlinux'

- name: "[MacOS] Install Github"
  community.general.homebrew:
    name: github-cli
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install Github"
  become: true
  community.general.pacman:
    name: github-cli
    state: present
  when: ansible_distribution == 'Archlinux'

- name: "[MacOS] Install exa"
  community.general.homebrew_cask:
    name: exa
    state: present
  when: ansible_distribution == 'MacOSX'
- name: "[Arch] Install exa"
  become: true
  community.general.pacman:
    name: exa
    state: present
  when: ansible_distribution == 'Archlinux'
